version: "3"
services:
  prometheus:
    container_name: webflux-vaadin-chat-prometheus
    image: prom/prometheus:v3.1.0
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: "host" # to test locally running service
  grafana:
    container_name: webflux-vaadin-chat-grafana
    image: grafana/grafana:11.4.0
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: "host" # to test locally running service

  sonar:
    container_name: webflux-vaadin-chat-sonarqube
    image: sonarqube:25.3.0.104237-community
    # Forced authentication redirect for UI is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete SONAR_FORCEAUTHENTICATION variable or set SONAR_FORCEAUTHENTICATION=true
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000
