git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : sample-webflux-vaadin-chat

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,org.ujar.webfluxvaadinchat

logging :
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    prometheus :
      enabled : true

ujar :
  build :
    description : '@project.description@'
    relative-path : ${SWAGGER_UI_RELATIVE_PATH:/}
    version : '@project.version@'

